/**


 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Indicates with which company the user is associated. At the moment there are   [KE] Kaufmann/-Frau im Einzelhandel   [KF] Kaufmann/-Frau im Feinkost   [VE] Verkäufer/-in   [VF] Verkäufer/-in Feinkost   [F]  Fleischer/-in   [FF] Fachverkäufer/-in Fleischerei   [S]  Sonstige
 */
export interface UserTypes {
}
