/**


 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface User {
    /**
     * Unique identifier representing a specific user.
     */
    id?: number;

    userType?: User.UserTypeEnum;


}
export namespace User {

    export enum UserTypeEnum {
        KE = <any> 'KE'
    }
}
